Avoid calling vs_len(ptr) from within pure procs
Introducing vstrs to the dom resulted in gfortran (but
not g95) flagging errors:

m_dom_dom.F90:9086.18:

          n = len(arg%ownerDocument%docExtras%xds%intSubset)
                 1
Error: Procedure argument at (1) is local to a PURE procedure and has the POINTER attribute
m_dom_dom.F90:7969.14:

      n = len(arg%docExtras%xds%inputEncoding)
             1
Error: Procedure argument at (1) is local to a PURE procedure and has the POINTER attribute
m_dom_dom.F90:7919.14:

      n = len(arg%docExtras%xds%encoding)
             1
Error: Procedure argument at (1) is local to a PURE procedure and has the POINTER attribute

It looks like we can avoid this by changing type(node), pointer to
type(node), intent(in)... and I'm not sure I can see which constraint in 12.6 is being
violated here.